apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: users.htpasswd
    mappingMethod: claim
    type: HTPPasswd
    htpasswd:
        fileData:
          name: htpass-secret
      
